server:
  port: 8270

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bdmicio
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    open-in-view: false
